name: Push image to GitHub Docker registry

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            netwerkdigitaalerfgoed/bikeshed:${{ steps.vars.outputs.version_tag }}
            netwerkdigitaalerfgoed/bikeshed:latest
