name: Push image to GitHub Docker registry

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            netwerkdigitaalerfgoed/bikeshed:${{ github.ref_name }}
            netwerkdigitaalerfgoed/bikeshed:latest
